- name: Run commands on ESXi hosts
  command: esxcli system maintenanceMode set --enable true

- name: Run commands on ESXi hosts
  command: Marc's command

- name: Run commands on ESXi hosts
  command: esxcli system maintenanceMode set --enable false

- name: Enter VSAN-Compliant Maintenance Mode
  community.vmware.vmware_maintenancemode:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    vsan: ensureObjectAccessibility
    evacuate: yes
    timeout: 3600
    state: present
  delegate_to: localhost