- name: set host attributes
  community.vmware.vmware_tag_manager:
    validate_certs: no
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    object_name: '{{ item }}'
    object_type: HostSystem
    tag_names:
      - InstantClone.Maintenance:1
  loop: "{{ groups['hypervisors'] }}"
